In [3]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib import pyplot as plt
%matplotlib inline
import csv

In [8]:
PATH1 = "movies_combined.csv"
PATH2 = "ratings.csv"
PATH3 = "movies.csv"
movies, ratings, movies_ind = pd.read_csv(PATH1),pd.read_csv(PATH2), pd.read_csv(PATH3)

In [9]:
del ratings['timestamp']
ratings.set_index(['movieId', 'userId'], inplace=True)
ratings = ratings.unstack(0)
Rpca = ratings.copy()
Rpca.fillna(Rpca.mean(),inplace=True)
ratings = ratings.fillna(0)
ratings.head()

        rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10
userId
1          4.0    0.0    4.0    0.0    0.0    4.0    0.0    0.0    0.0    0.0
2          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5          4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

         ...                                                                   \
movieId  ...   193565 193567 193571 193573 193579 193581 193583 193585 193587
userId   ...
1        ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2        ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3        ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4        ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5        ...      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0


movieId 193609
userId
1          0.0
2          0.0
3          0.0
4          0.0
5          0.0

[5 rows x 9724 columns]

In [54]:
###Fill with average of the columns
#movies = ratings
#ratings.fillna(ratings.mean(),inplace=True)
#ratings.head(3)

#### Cosine similarity

In [10]:
# 7. use function in sklearn
similarity = cosine_similarity(ratings)

# 8. plot
#sns.heatmap(similarity, annot=True)
#plt.show()

In [11]:
#similarity[1]

#### PCA

In [12]:
X = Rpca - Rpca.mean()
X.mean()
pca = PCA(n_components=3)
pca.fit(X)
Xt = pca.transform(X)
pca.components_
pca.explained_variance_ratio_

array([0.04089924, 0.02026083, 0.01996139])

In [6]:
#del ratings['timestamp']