In [736]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import csv

In [737]:
PATH1 = "movies_combined.csv"
PATH2 = "ratings.csv"
PATH3 = "movies.csv"
movies, ratings, movies_ind = pd.read_csv(PATH1),pd.read_csv(PATH2), pd.read_csv(PATH3)

In [738]:
movies.head(5)

,movieId,title,userId,tag,timestamp,genres_(no genres listed),genres_Action,genres_Action|Adventure,genres_Action|Adventure|Animation,genres_Action|Adventure|Animation|Children,...,genres_Romance|Thriller,genres_Romance|War,genres_Romance|Western,genres_Sci-Fi,genres_Sci-Fi|IMAX,genres_Sci-Fi|Thriller,genres_Sci-Fi|Thriller|IMAX,genres_Thriller,genres_War,genres_Western
0,1,Toy Story (1995),336.0,pixar,1.139046e+09,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,Toy Story (1995),474.0,pixar,1.137207e+09,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,Toy Story (1995),567.0,fun,1.525286e+09,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,Jumanji (1995),62.0,fantasy,1.528844e+09,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,Jumanji (1995),62.0,magic board game,1.528844e+09,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [739]:
movies_ind.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [740]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [741]:
#if you want this in the data, you do it, because it's f%$#ing trouble
del ratings['timestamp']

In [742]:
#Make a data frame where each movie has just one row with ratings contained in individual columns of that row
ratings = ratings.pivot(index='movieId',columns ='userId',values = 'rating')
ratings.head(2)

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,NaN,NaN,4.0,NaN,4.5,NaN,NaN,NaN,...,4.0,NaN,4.0,3.0,4.0,2.5,4.0,2.5,3.0,5.0
2,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN,...,NaN,4.0,NaN,5.0,3.5,NaN,NaN,2.0,NaN,NaN

In [743]:
movies_small = movies[['movieId','title','tag']]

In [744]:
movies_small.head(5)

   movieId             title               tag
0        1  Toy Story (1995)             pixar
1        1  Toy Story (1995)             pixar
2        1  Toy Story (1995)               fun
3        2    Jumanji (1995)           fantasy
4        2    Jumanji (1995)  magic board game

In [745]:
movies_small.loc[1]

movieId                   1
title      Toy Story (1995)
tag                   pixar
Name: 1, dtype: object

In [746]:
movies_id = movies['movieId'] # as movies_small

In [747]:
movies.set_index('movieId',inplace=True)

In [748]:
movies['tag'].loc[7]

'remake'

In [749]:
movies_id[100]

70

In [750]:
movies.head(13)

,title,userId,tag,timestamp,genres_(no genres listed),genres_Action,genres_Action|Adventure,genres_Action|Adventure|Animation,genres_Action|Adventure|Animation|Children,genres_Action|Adventure|Animation|Children|Comedy,...,genres_Romance|Thriller,genres_Romance|War,genres_Romance|Western,genres_Sci-Fi,genres_Sci-Fi|IMAX,genres_Sci-Fi|Thriller,genres_Sci-Fi|Thriller|IMAX,genres_Thriller,genres_War,genres_Western
movieId,,,,,,,,,,,,,,,,,,,,,
1,Toy Story (1995),336.0,pixar,1.139046e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Toy Story (1995),474.0,pixar,1.137207e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Toy Story (1995),567.0,fun,1.525286e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Jumanji (1995),62.0,fantasy,1.528844e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Jumanji (1995),62.0,magic board game,1.528844e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Jumanji (1995),62.0,Robin Williams,1.528844e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Jumanji (1995),474.0,game,1.137376e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Grumpier Old Men (1995),289.0,moldy,1.143425e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Grumpier Old Men (1995),289.0,old,1.143425e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Waiting to Exhale (1995),NaN,None,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Father of the Bride Part II (1995),474.0,pregnancy,1.137374e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Father of the Bride Part II (1995),474.0,remake,1.137374e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Heat (1995),NaN,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [751]:
for i in range(8,8):
    yes = movies['tag'].loc[10]
    no = pd.DataFrame(yes)

In [752]:
yes

movieId
3    moldy
3      old
Name: tag, dtype: object

In [753]:
for i in movies_id:
    yes = movies['tag'].loc[1]
    no = pd.DataFrame(yes)
    for x, row in enumerate(no.itertuples(),1):
        movies_ind[x] = row.tag

In [754]:
movies_ind

,movieId,title,genres,1,2,3
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,pixar,pixar,fun
1,2,Jumanji (1995),Adventure|Children|Fantasy,pixar,pixar,fun
2,3,Grumpier Old Men (1995),Comedy|Romance,pixar,pixar,fun
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,pixar,pixar,fun
4,5,Father of the Bride Part II (1995),Comedy,pixar,pixar,fun
5,6,Heat (1995),Action|Crime|Thriller,pixar,pixar,fun
6,7,Sabrina (1995),Comedy|Romance,pixar,pixar,fun
7,8,Tom and Huck (1995),Adventure|Children,pixar,pixar,fun
8,9,Sudden Death (1995),Action,pixar,pixar,fun
9,10,GoldenEye (1995),Action|Adventure|Thriller,pixar,pixar,fun
10,11,"American President, The (1995)",Comedy|Drama|Romance,pixar,pixar,fun
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,pixar,pixar,fun
12,13,Balto (1995),Adventure|Animation|Children,pixar,pixar,fun
13,14,Nixon (1995),Drama,pixar,pixar,fun
14,15,Cutthroat Island (1995),Action|Adventure|Romance,pixar,pixar,fun
15,16,Casino (1995),Crime|Drama,pixar,pixar,fun
16,17,Sense and Sensibility (1995),Drama|Romance,pixar,pixar,fun
17,18,Four Rooms (1995),Comedy,pixar,pixar,fun
18,19,Ace Ventura: When Nature Calls (1995),Comedy,pixar,pixar,fun
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,pixar,pixar,fun
20,21,Get Shorty (1995),Comedy|Crime|Thriller,pixar,pixar,fun
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,pixar,pixar,fun
22,23,Assassins (1995),Action|Crime|Thriller,pixar,pixar,fun
23,24,Powder (1995),Drama|Sci-Fi,pixar,pixar,fun
24,25,Leaving Las Vegas (1995),Drama|Romance,pixar,pixar,fun
25,26,Othello (1995),Drama,pixar,pixar,fun
26,27,Now and Then (1995),Children|Drama,pixar,pixar,fun
27,28,Persuasion (1995),Drama|Romance,pixar,pixar,fun
28,29,"City of Lost Children, The (CitÃ© des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,pixar,pixar,fun
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,pixar,pixar,fun
...,...,...,...,...,...,...
9712,188189,Sorry to Bother You (2018),Comedy|Fantasy|Sci-Fi,pixar,pixar,fun
9713,188301,Ant-Man and the Wasp (2018),Action|Adventure|Comedy|Fantasy|Sci-Fi,pixar,pixar,fun
9714,188675,Dogman (2018),Crime|Drama,pixar,pixar,fun
9715,188751,Mamma Mia: Here We Go Again! (2018),Comedy|Romance,pixar,pixar,fun
9716,188797,Tag (2018),Comedy,pixar,pixar,fun
9717,188833,The Man Who Killed Don Quixote (2018),Adventure|Comedy|Fantasy,pixar,pixar,fun
9718,189043,Boundaries (2018),Comedy|Drama,pixar,pixar,fun
9719,189111,Spiral (2018),Documentary,pixar,pixar,fun
9720,189333,Mission: Impossible - Fallout (2018),Action|Adventure|Thriller,pixar,pixar,fun
9721,189381,SuperFly (2018),Action|Crime|Thriller,pixar,pixar,fun
9722,189547,Iron Soldier (2010),Action|Sci-Fi,pixar,pixar,fun
9723,189713,BlacKkKlansman (2018),Comedy|Crime|Drama,pixar,pixar,fun
9724,190183,The Darkest Minds (2018),Sci-Fi|Thriller,pixar,pixar,fun
9725,190207,Tilt (2011),Drama|Romance,pixar,pixar,fun
9726,190209,Jeff Ross Roasts the Border (2017),Comedy,pixar,pixar,fun
9727,190213,John From (2015),Drama,pixar,pixar,fun
9728,190215,Liquid Truth (2017),Drama,pixar,pixar,fun
9729,190219,Bunny (1998),Animation,pixar,pixar,fun
9730,190221,Hommage Ã Zgougou (et salut Ã Sabine Mamou) (2...,Documentary,pixar,pixar,fun
9731,191005,Gintama (2017),Action|Adventure|Comedy|Sci-Fi,pixar,pixar,fun
9732,193565,Gintama: The Movie (2010),Action|Animation|Comedy|Sci-Fi,pixar,pixar,fun
9733,193567,anohana: The Flower We Saw That Day - The Movi...,Animation|Drama,pixar,pixar,fun
9734,193571,Silver Spoon (2014),Comedy|Drama,pixar,pixar,fun
9735,193573,Love Live! The School Idol Movie (2015),Animation,pixar,pixar,fun
9736,193579,Jon Stewart Has Left the Building (2015),Documentary,pixar,pixar,fun
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,pixar,pixar,fun
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,pixar,pixar,fun
9739,193585,Flint (2017),Drama,pixar,pixar,fun
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,pixar,pixar,fun
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,pixar,pixar,fun

In [3]:
##Class

In [4]:
df = pd.read_excel(PATH)
print('''
     Julians Movie Recommender:
     
     Enter your favorite genre or reviwer 
     and the program will recommend a movie
      
     ''')

print('enter a genre (or leave it empty): ', end = '')
genre = input

SyntaxError: invalid syntax (<ipython-input-4-cf7f41e9cf99>, line 3)

In [42]:
merge = pd.merge(df,df2, left_index = True, right_index=True,how = 'outer')
merge.head(2)

,title,userId_x,tag,timestamp_x,genres_(no genres listed),genres_Action,genres_Action|Adventure,genres_Action|Adventure|Animation,genres_Action|Adventure|Animation|Children,genres_Action|Adventure|Animation|Children|Comedy,...,genres_Sci-Fi,genres_Sci-Fi|IMAX,genres_Sci-Fi|Thriller,genres_Sci-Fi|Thriller|IMAX,genres_Thriller,genres_War,genres_Western,userId_y,rating,timestamp_y
movieId,,,,,,,,,,,,,,,,,,,,,
1,Toy Story (1995),336.0,pixar,1.139046e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.0,4.0,964982703.0
1,Toy Story (1995),336.0,pixar,1.139046e+09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,5.0,4.0,847434962.0

In [46]:
merge.pivot(columns='rating')

ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
if genre:
    g = df[df['Genre'] = genre]
    else:
        g= df
g.sort_values('Rating', ascending = False)
print(result.head(3).sample(1))

In [ ]:
# write simple ui
# print explanatory text
# ask user for genre
# and fav reviewer
# either can be empty
# return the best scoring hit

In [5]:
#ui

In [6]:
#recommender

In [ ]:
#database

In [ ]:
###End of class

In [3]:
# produce clean unique index
df.sort_values(by=['Name', 'Genre', 'Reviewer'], inplace=True)
clean = df.drop_duplicates().dropna()

In [4]:
long = clean.set_index(['Name', 'Genre', 'Reviewer'])

In [5]:
# mean rating per genre
print(long.unstack(1).mean())

        Genre
Rating  Action             1.500000
        Adventure          1.000000
        Biopic             4.000000
        Cartoon            3.500000
        Comedy             3.818182
        Comedy / Trippy    4.000000
        Crime              4.400000
        Dark Comedy        4.500000
        Data Science       3.750000
        Drama              4.250000
        Fantasy            4.000000
        Farce              1.000000
        Horror             3.333333
        Kaiju              1.000000
        Musical            1.500000
        Mystery            5.000000
        Revolutionary      4.000000
        Samurai            4.000000
        Sci-Fi             4.200000
        Thriller           5.000000
        Trippy             4.000000
dtype: float64

In [6]:
df.head(5)

                    Name   Genre  Rating  Reviewer
0           12 Angry Men   Drama     1.0    Felipe
1             12 Monkeys  Sci-Fi     4.0    Helena
2  2001: A Space Odyssey  Sci-Fi     5.0  Matthias
3       A Beautiful Mind  Biopic     4.0  Matthias
4          A Quiet Place   Drama     5.0      Nick

In [7]:
y = df['Rating']
###Need to convert your categories into one hot values!!!
X = df[['Name','Genre','Reviewer']]
from sklearn.preprocessing import LabelEncoder
m = LabelEncoder()
m.fit_transform(X['Genre'])
pd.get_dummies(X['Genre'])

,Action,Adventure,Biopic,Cartoon,Comedy,Comedy / Trippy,Crime,Crime/Drama?,Dark Comedy,Data Science,...,Farce,Horror,Kaiju,Musical,Mystery,Revolutionary,Samurai,Sci-Fi,Thriller,Trippy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
14,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
77,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
27,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
49,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
51,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
53,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
57,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
60,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
61,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
62,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
65,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
66,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
67,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
68,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
69,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
70,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
71,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
76,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [8]:
X.head(3)

                    Name   Genre  Reviewer
0           12 Angry Men   Drama    Felipe
1             12 Monkeys  Sci-Fi    Helena
2  2001: A Space Odyssey  Sci-Fi  Matthias

Lets first try a logistic regression!

In [9]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y)
print(Xtrain.shape, Xtest.shape, ytrain.shape, ytest.shape)
# create a decision tree
m = DecisionTreeClassifier(max_depth=3)

(60, 3) (21, 3) (60,) (21,)

Select a genre 
from this genre selct the top movies?